services:
  postgres:
    image: postgres:16-alpine
    container_name: granavista-bd
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: granavista
      POSTGRES_PASSWORD: granavista_dev
      POSTGRES_DB: granavista
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: